![Python_logo](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)


 # **Cortex Game: Round2--Conditional Amount**

Please note that you need to run this notebook 'Round2--Conditional Amount' first, before running the notebook 'Round2--Probability of Giving'.

> Before playing the game, you need to connect to SASPy first.
>
>> If it is your first time, please follow the 4 steps mentioned below!

***
## **Connect to SASPy**

**0- Connect to your Google Drive folder**

In [2]:
my_folder = "/content/drive/MyDrive/COLAB-SAS"

from google.colab import drive
drive.mount('/content/drive')

# Change the following code to set your Drive folder
import os
os.chdir(my_folder)
!pwd

Mounted at /content/drive
/content/drive/MyDrive/COLAB-SAS

**1- Make sure that your Python version is 3.3 or higher as well as your Java version is 1.8.0_162 or higher**

In [3]:
!echo "Python is at" $(which python)
!python --version

Python is at /usr/local/bin/python
Python 3.8.15

In [4]:
!echo "Java is at" $(which java)
!/usr/bin/java -version

Java is at /usr/bin/java
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu218.04, mixed mode, sharing)

**2- Install SASPy**

In [5]:
pip install saspy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting saspy
  Downloading saspy-4.4.1.tar.gz (9.9 MB)
     |████████████████████████████████| 9.9 MB 6.2 MB/s
Building wheels for collected packages: saspy
  Building wheel for saspy (setup.py) ... done
  Created wheel for saspy: filename=saspy-4.4.1-py3-none-any.whl size=9937304 sha256=6b800da6db8781b040c80d9025ff3cdde35e86552c336c1d6905e56e1d6bbfa3
  Stored in directory: /root/.cache/pip/wheels/0a/f6/ab/f7173c8a824856c66f6fd50194bb8fd3ef93fb4f1824be8d0c
Successfully built saspy
Installing collected packages: saspy
Successfully installed saspy-4.4.1

**3- Create the configuration file "sascfg_personal.py"**
Please, check that your Home Region is correct, you can check it at [ODA-SAS](https://welcome.oda.sas.com/home)

In [6]:
%%writefile sascfg_personal.py
SAS_config_names=['oda']
oda = {'java' : '/usr/bin/java',
#US Home Region 1
'iomhost' : ['odaws01-usw2.oda.sas.com','odaws02-usw2.oda.sas.com','odaws03-usw2.oda.sas.com','odaws04-usw2.oda.sas.com'],
#US Home Region 2
#'iomhost' : ['odaws01-usw2-2.oda.sas.com','odaws02-usw2-2.oda.sas.com'],
#European Home Region 1
#'iomhost' : ['odaws01-euw1.oda.sas.com','odaws02-euw1.oda.sas.com'],
#Asia Pacific Home Region 1
#'iomhost' : ['odaws01-apse1.oda.sas.com','odaws02-apse1.oda.sas.com'],
#Asia Pacific Home Region 2
#'iomhost' : ['odaws01-apse1-2.oda.sas.com','odaws02-apse1-2.oda.sas.com'],
'iomport' : 8591,
'authkey' : 'oda',
'encoding' : 'utf-8'
}

Overwriting sascfg_personal.py

**4- Create your .authinfo**

If there is no .authinfo file, you can create this

In [7]:
%%writefile .authinfo
oda user u62400121 password Ibra$?182001

Overwriting .authinfo

Copy this file to home

In [8]:
!cp .authinfo ~/.authinfo

**5- Establish Connection (Need to do this step each time you use SASPy)**

In [9]:
import saspy
sas_session = saspy.SASsession(cfgfile=os.path.join(
    my_folder,"sascfg_personal.py"))
sas_session

Using SAS Config named: oda
SAS Connection established. Subprocess id is 367

Access Method         = IOM
SAS Config name       = oda
SAS Config file       = /content/drive/MyDrive/COLAB-SAS/sascfg_personal.py
WORK Path             = /saswork/SAS_work438D00003A91_odaws01-usw2.oda.sas.com/SAS_work44B700003A91_odaws01-usw2.oda.sas.com/
SAS Version           = 9.04.01M6P11072018
SASPy Version         = 4.4.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf-8
SAS process Pid value = 14993

***
## Connect to Cortex Data Sets

Load Cortex datasets from SAS Studio

In [10]:
ps = sas_session.submit("""
    libname cortex '~/my_shared_file_links/u39842936/Cortex Data Sets';
    """)
print(ps["LOG"])

5                                                          The SAS System                      Friday, December  2, 2022 09:17:00 AM

24         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
24       ! ods graphics on / outputfmt=png;
25
26
27             libname cortex '~/my_shared_file_links/u39842936/Cortex Data Sets';
28
29
30
31         ods html5 (id=saspy_internal) close;ods listing;
32

6                                                          The SAS System                      Friday, December  2, 2022 09:17:00 AM

33

For local Jupyter

In [11]:
#%%SAS sas_session
#libname cortex '~/my_shared_file_links/u39842936/Cortex Data Sets';

### Transform cloud SAS dataset to Python dataframe (pandas)

> For reference: 

> 1- [Pandas library](https://pandas.pydata.org/docs/user_guide/index.html)

> 2- [sklearn.model_selection for data partition](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [55]:
import pandas as pd

#comment: Transform cloud sas dataset to python dataframe(pandas) ==> might take some time.

data1 = sas_session.sasdata2dataframe(
table='hist',
libref='cortex'
)

data2 = sas_session.sasdata2dataframe(
table='target_rd2',
libref='cortex'
)
data1

,ID,LastName,FirstName,Woman,Age,Salary,Education,City,SeniorList,NbActivities,Referrals,Recency,Frequency,Seniority,TotalGift,MinGift,MaxGift,GaveLastYear,AmtLastYear
0,2000001.0,ROMMES,RODNEY,0.0,25.0,107200.0,University / College,City,2.0,0.0,0.0,1.0,2.0,2.0,1010.0,10.0,1000.0,0.0,0.0
1,2000002.0,RAMIREZ,SHARON,1.0,38.0,15800.0,High School,Rural,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,2000003.0,TSOSIE,KAREN,1.0,37.0,57400.0,University / College,Rural,5.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,2000004.0,LEE,MARY,1.0,78.0,23700.0,High School,Rural,3.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,2000005.0,HUMPHRES,ANGIE,1.0,34.0,71900.0,University / College,Rural,8.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2999996.0,SCHUBERT,FRANCES,1.0,29.0,15100.0,High School,Suburban,8.0,3.0,2.0,5.0,1.0,5.0,20.0,20.0,20.0,0.0,0.0
999996,2999997.0,LUGGE,MARY,1.0,22.0,7000.0,High School,Suburban,10.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
999997,2999998.0,ROY,REGINALD,0.0,17.0,1000.0,High School,City,10.0,1.0,1.0,1.0,1.0,1.0,20.0,20.0,20.0,0.0,0.0
999998,2999999.0,LIBERTI,PAMELA,1.0,32.0,43900.0,University / College,Rural,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
999999,3000000.0,BELL,SYBIL,1.0,50.0,52400.0,University / College,Suburban,4.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [56]:
data2

               ID  Contact  GaveThisYear  AmtThisYear
0       2000001.0      1.0           0.0          0.0
1       2000002.0      1.0           0.0          0.0
2       2000003.0      0.0           0.0          0.0
3       2000004.0      1.0           1.0         20.0
4       2000005.0      0.0           0.0          0.0
...           ...      ...           ...          ...
999995  2999996.0      0.0           0.0          0.0
999996  2999997.0      0.0           0.0          0.0
999997  2999998.0      0.0           0.0          0.0
999998  2999999.0      0.0           1.0         20.0
999999  3000000.0      0.0           0.0          0.0

[1000000 rows x 4 columns]

## Merge the Data

In [57]:
#Step1 Merge the Data
data_merge = pd.merge(data1, data2, on=["ID"],how="right")
data_merge = data_merge.loc[(data_merge['GaveThisYear'] ==1)]
data_merge.sample(2)

,ID,LastName,FirstName,Woman,Age,Salary,Education,City,SeniorList,NbActivities,...,Frequency,Seniority,TotalGift,MinGift,MaxGift,GaveLastYear,AmtLastYear,Contact,GaveThisYear,AmtThisYear
501347,2501348.0,BARBER,BARBARA,1.0,39.0,69300.0,High School,Rural,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0,10.0
702701,2702702.0,FERRO,RAYMOND,0.0,72.0,49300.0,University / College,Rural,7.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,20.0,0.0,1.0,50.0

In [58]:
data1.isnull().sum()

ID                   0
LastName            23
FirstName            4
Woman                0
Age                  0
Salary               0
Education            0
City                 0
SeniorList           0
NbActivities         0
Referrals            0
Recency         663666
Frequency       663666
Seniority       663666
TotalGift       663666
MinGift         663666
MaxGift         663666
GaveLastYear         0
AmtLastYear          0
dtype: int64

In [59]:
data2.isnull().sum()

ID              0
Contact         0
GaveThisYear    0
AmtThisYear     0
dtype: int64

In [60]:
data_merge.isnull().sum()

ID                  0
LastName            3
FirstName           0
Woman               0
Age                 0
Salary              0
Education           0
City                0
SeniorList          0
NbActivities        0
Referrals           0
Recency         81024
Frequency       81024
Seniority       81024
TotalGift       81024
MinGift         81024
MaxGift         81024
GaveLastYear        0
AmtLastYear         0
Contact             0
GaveThisYear        0
AmtThisYear         0
dtype: int64

In [61]:
data_merge.dtypes

ID              float64
LastName         object
FirstName        object
Woman           float64
Age             float64
Salary          float64
Education        object
City             object
SeniorList      float64
NbActivities    float64
Referrals       float64
Recency         float64
Frequency       float64
Seniority       float64
TotalGift       float64
MinGift         float64
MaxGift         float64
GaveLastYear    float64
AmtLastYear     float64
Contact         float64
GaveThisYear    float64
AmtThisYear     float64
dtype: object

## Treating Missing Values

>Please be aware that deleting all missing values can induce a selection bias. 
Some missing values are very informative. For example, when MinGift is missing, it means that the donor never gave in the past 10 years (leading to but excluding last year). Instead of deleting this information, replacing it by 0 is more appropriate!

> A good understanding of the business case and the data can help you come up with more appropriate strategies to deal with missing values.

In [62]:
data_merge = data_merge.drop(['LastName', 'FirstName', 'Education', 'City'], axis=1)

data_merge[['MinGift']] = data_merge[['MinGift']].fillna(0)

data_merge[['MaxGift']] = round(data_merge[['MaxGift']].transform(lambda x: x.fillna(x.mean())),2)

data_merge[['TotalGift']] = round(data_merge[['TotalGift']].transform(lambda x: x.fillna(x.mean())),2)

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer(imputation_order='ascending',max_iter=10,random_state=42,n_nearest_features=None)

for i in data_merge:
  data_merge.loc[:,i]=imputer.fit_transform(data_merge[[i]])

data_merge.sample(5)

,ID,Woman,Age,Salary,SeniorList,NbActivities,Referrals,Recency,Frequency,Seniority,TotalGift,MinGift,MaxGift,GaveLastYear,AmtLastYear,Contact,GaveThisYear,AmtThisYear
595992,2595993.0,0.0,60.0,169900.0,0.0,0.0,0.0,2.75091,1.985796,4.674952,134.86,0.0,106.67,0.0,0.0,0.0,1.0,30.0
590333,2590334.0,1.0,22.0,1700.0,8.0,1.0,0.0,2.75091,1.985796,4.674952,134.86,0.0,106.67,0.0,0.0,1.0,1.0,10.0
453778,2453779.0,0.0,44.0,167900.0,10.0,2.0,1.0,5.00000,1.000000,5.000000,75.00,75.0,75.00,0.0,0.0,0.0,1.0,20.0
633362,2633363.0,1.0,48.0,25800.0,9.0,2.0,3.0,2.75091,1.985796,4.674952,134.86,0.0,106.67,0.0,0.0,0.0,1.0,20.0
365125,2365126.0,1.0,40.0,11000.0,4.0,0.0,0.0,2.75091,1.985796,4.674952,134.86,0.0,106.67,0.0,0.0,1.0,1.0,15.0

## Data Partition

In [63]:
# The code below is an illustration on how to sample data on train and validation samples.
# You could use another library or a built-in function to perform sampling.

from sklearn.model_selection import train_test_split
train, validation = train_test_split(data_merge, test_size=0.3,random_state=5678) # you can change the percentage
train.sample(5)

,ID,Woman,Age,Salary,SeniorList,NbActivities,Referrals,Recency,Frequency,Seniority,TotalGift,MinGift,MaxGift,GaveLastYear,AmtLastYear,Contact,GaveThisYear,AmtThisYear
530034,2530035.0,1.0,37.0,113000.0,3.0,2.0,1.0,2.75091,1.985796,4.674952,134.86,0.0,106.67,1.0,20.0,0.0,1.0,20.0
429512,2429513.0,0.0,62.0,71800.0,0.0,0.0,0.0,2.75091,1.985796,4.674952,134.86,0.0,106.67,0.0,0.0,0.0,1.0,50.0
107617,2107618.0,1.0,68.0,32900.0,0.0,0.0,0.0,2.75091,1.985796,4.674952,134.86,0.0,106.67,0.0,0.0,1.0,1.0,25.0
611139,2611140.0,0.0,34.0,178800.0,9.0,8.0,4.0,2.00000,6.000000,9.000000,755.00,10.0,400.00,0.0,0.0,0.0,1.0,40.0
935218,2935219.0,1.0,55.0,66100.0,9.0,2.0,0.0,7.00000,1.000000,7.000000,25.00,25.0,25.00,0.0,0.0,0.0,1.0,100.0


## Prebuilt Models

***
### Linear Regression Model


> The [sk-learn library]( https://scikit-learn.org/stable/index.html) offers more advanced models.

In [64]:
from sklearn import linear_model

#comment: it's numpy array
X_train = train[['Age', 'Salary','Contact','MinGift', 'GaveLastYear','AmtLastYear','Woman', 'NbActivities' ]] 
Y_train = train['AmtThisYear']
X_valid = validation[['Age', 'Salary','Contact','MinGift', 'GaveLastYear','AmtLastYear','Woman', 'NbActivities']] 
Y_valid = validation['AmtThisYear']

regr = linear_model.LinearRegression()

regr.fit(X_train,Y_train)

regr_predict=regr.predict(X_valid)

print(regr_predict)

[ 52.89652623  12.05144674 124.04693958 ...  44.03982959  62.37379967
  54.44548191]

In [22]:
#you can change the criteria

import numpy as np
from sklearn import metrics
#MAE
print(metrics.mean_absolute_error(Y_valid,regr_predict))
#MSE
print(metrics.mean_squared_error(Y_valid,regr_predict))
#RMSE
print(np.sqrt(metrics.mean_squared_error(Y_valid,regr_predict)))

64.43397454833679
57897.047617862365
240.61805339139116

## Regression Tree Model（Py）

In [84]:
from sklearn.tree import DecisionTreeRegressor

X_train = train[['Age', 'Salary','Contact','MinGift', 'GaveLastYear','AmtLastYear','Woman', 'NbActivities' ]] 
Y_train = train['AmtThisYear']
X_valid = validation[['Age', 'Salary','Contact','MinGift', 'GaveLastYear','AmtLastYear','Woman', 'NbActivities' ]] 
Y_valid = validation['AmtThisYear']

DT_model = DecisionTreeRegressor(max_depth=5, random_state=0).fit(X_train,Y_train)
DT_predict = DT_model.predict(X_valid) #Predictions on Testing data
print(DT_predict)

[ 51.54726819  26.64407778 138.66797258 ...  53.92518939  53.29201102
  43.30381785]

In [85]:
#you can change the criteria
#MAE
print(metrics.mean_absolute_error(Y_valid,DT_predict))
#MSE
print(metrics.mean_squared_error(Y_valid,DT_predict))
#RMSE
print(np.sqrt(metrics.mean_squared_error(Y_valid,DT_predict)))

63.14143463747639
53032.414739318454
230.28767821861084

## XGBoost

In [65]:
import xgboost as xgb
model = xgb.XGBClassifier()
model.fit(X_train, Y_train)
print(); print(model)

XGBClassifier(objective='multi:softprob')

In [66]:
expected_y  = Y_valid
predicted_y = model.predict(X_valid)

print(metrics.classification_report(expected_y, predicted_y))
print(metrics.confusion_matrix(expected_y, predicted_y))

              precision    recall  f1-score   support

        10.0       0.33      0.02      0.04      7018
        15.0       0.00      0.00      0.00       752
        20.0       0.29      0.99      0.45     13037
        25.0       0.00      0.00      0.00      4915
        30.0       0.00      0.00      0.00      4261
        40.0       0.25      0.00      0.00      3446
        50.0       0.00      0.00      0.00      3423
        60.0       0.00      0.00      0.00       204
        70.0       0.00      0.00      0.00       215
        75.0       0.00      0.00      0.00      1881
        80.0       0.00      0.00      0.00       202
        90.0       0.00      0.00      0.00       227
       100.0       0.00      0.00      0.00      1818
       120.0       0.00      0.00      0.00       177
       125.0       0.00      0.00      0.00       154
       150.0       0.00      0.00      0.00       684
       175.0       0.00      0.00      0.00        89
       200.0       0.00      0.00      0.00       510
       225.0       0.00      0.00      0.00        40
       250.0       0.00      0.00      0.00       348
       300.0       0.00      0.00      0.00       184
       350.0       0.00      0.00      0.00        30
       400.0       0.00      0.00      0.00       174
       450.0       0.00      0.00      0.00        32
       500.0       0.00      0.00      0.00       433
       550.0       0.00      0.00      0.00        20
       600.0       0.00      0.00      0.00        24
       650.0       0.00      0.00      0.00        28
       700.0       0.00      0.00      0.00        12
       750.0       0.00      0.00      0.00       132
       800.0       0.00      0.00      0.00        16
       900.0       0.00      0.00      0.00         6
      1000.0       0.00      0.00      0.00       107
      1200.0       0.00      0.00      0.00        27
      1400.0       0.00      0.00      0.00         6
      1500.0       0.00      0.00      0.00        56
      1700.0       0.00      0.00      0.00        16
      2000.0       0.00      0.00      0.00        52
      2500.0       0.00      0.00      0.00        22
      3000.0       0.00      0.00      0.00        17
      3500.0       0.00      0.00      0.00         3
      4000.0       0.00      0.00      0.00        12
      5000.0       0.00      0.00      0.00        17
      6000.0       0.00      0.00      0.00         1
      7000.0       0.00      0.00      0.00         3
      8000.0       0.00      0.00      0.00         1
      9000.0       0.00      0.00      0.00         1
     10000.0       0.00      0.00      0.00         5

    accuracy                           0.29     44838
   macro avg       0.02      0.02      0.01     44838
weighted avg       0.16      0.29      0.14     44838

[[  152     0  6864 ...     0     0     0]
 [    9     0   742 ...     0     0     0]
 [  129     0 12903 ...     0     0     0]
 ...
 [    0     0     1 ...     0     0     0]
 [    0     0     1 ...     0     0     0]
 [    1     0     4 ...     0     0     0]]

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [67]:
DT_predict = predicted_y

In [68]:
#you can change the criteria
#MAE
print(metrics.mean_absolute_error(expected_y,DT_predict))
#MSE
print(metrics.mean_squared_error(expected_y,DT_predict))
#RMSE
print(np.sqrt(metrics.mean_squared_error(expected_y,DT_predict)))

47.724028725634504
58552.89932646416
241.9770636371641

### **Other models may also be helpful for this game**

Reference: https://scikit-learn.org/stable/supervised_learning.html

## Scoring New Data

### Prepare data for scoring

In [69]:
data3 = sas_session.sasdata2dataframe(
table='score',
libref='cortex'
)
data4 = sas_session.sasdata2dataframe(
table='score_rd2_contact',
libref='cortex'
)
data5 = sas_session.sasdata2dataframe(
table='score_rd2_nocontact',
libref='cortex'
)

 ### Score new data based on your champion model
 
 Pick your champion model from previous steps and use it to predict next year donations. 
 
 In this case, the linear regression model performed better than the regression tree based on the MSE criteria.

### Predict 'amount given' for members who were contacted

In [70]:
scoring_data_contact = pd.merge(data3, data4, on=["ID"],how="right")

scoring_data_contact = scoring_data_contact.drop(['LastName', 'FirstName', 'Education', 'City'], axis=1)

scoring_data_contact[['MinGift']] = scoring_data_contact[['MinGift']].fillna(0)

scoring_data_contact[['MaxGift']] = round(scoring_data_contact[['MaxGift']].transform(lambda x: x.fillna(x.mean())),2)

scoring_data_contact[['TotalGift']] = round(scoring_data_contact[['TotalGift']].transform(lambda x: x.fillna(x.mean())),2)

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer(imputation_order='ascending',max_iter=10,random_state=42,n_nearest_features=None)

for i in scoring_data_contact:
  scoring_data_contact.loc[:,i]=imputer.fit_transform(scoring_data_contact[[i]])

scoring_data_contact.head()

X = scoring_data_contact[['Age', 'Salary','Contact','MinGift', 'AmtLastYear','GaveLastYear','Woman', 'NbActivities' ]] 

regr_predict_contact=regr.predict(X)

scoring_data_contact['Prediction'] = regr_predict_contact

scoring_data_contact= scoring_data_contact[['ID','Prediction']]
scoring_data_contact = scoring_data_contact.rename({'Prediction': 'AmtContact'}, axis=1) 
scoring_data_contact.head()

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

          ID  AmtContact
0  2000001.0   66.934246
1  2000002.0   60.776367
2  2000003.0   69.599856
3  2000004.0   39.476625
4  2000005.0   74.992426

### Predict 'amount given' for members who were not contacted

In [71]:
scoring_data_nocontact = pd.merge(data3, data5, on=["ID"],how="right")

scoring_data_nocontact = scoring_data_nocontact.drop(['LastName', 'FirstName', 'Education', 'City'], axis=1)

scoring_data_nocontact[['MinGift']] = scoring_data_nocontact[['MinGift']].fillna(0)

scoring_data_nocontact[['MaxGift']] = round(scoring_data_nocontact[['MaxGift']].transform(lambda x: x.fillna(x.mean())),2)

scoring_data_nocontact[['TotalGift']] = round(scoring_data_nocontact[['TotalGift']].transform(lambda x: x.fillna(x.mean())),2)

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer(imputation_order='ascending',max_iter=10,random_state=42,n_nearest_features=None)

for i in scoring_data_nocontact:
  scoring_data_nocontact.loc[:,i]=imputer.fit_transform(scoring_data_nocontact[[i]])

scoring_data_nocontact.head()

X = scoring_data_nocontact[['Age', 'Salary','Contact','MinGift','AmtLastYear', 'GaveLastYear','Woman', 'NbActivities' ]] 

regr_predict_nocontact=regr.predict(X)

scoring_data_nocontact['Prediction'] = regr_predict_nocontact

scoring_data_nocontact= scoring_data_nocontact[['ID','Prediction']]
scoring_data_nocontact = scoring_data_nocontact.rename({'Prediction': 'AmtNoContact'}, axis=1) 
scoring_data_nocontact.head()

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

          ID  AmtNoContact
0  2000001.0     69.239842
1  2000002.0     63.081963
2  2000003.0     71.905452
3  2000004.0     41.782221
4  2000005.0     77.298022

In [72]:
result_Amt = pd.merge(scoring_data_contact, scoring_data_nocontact, on=["ID"],how="right")
result_Amt.sort_values(by=['ID'], inplace=True)
result_Amt[['ID']] = result_Amt[['ID']].astype(int)
result_Amt.head(3)

        ID  AmtContact  AmtNoContact
0  2000001   66.934246     69.239842
1  2000002   60.776367     63.081963
2  2000003   69.599856     71.905452

## Exporting Results to a CSV File

In [73]:
result_Amt.to_csv('Round2_Output_amt.csv', index=False)

In [74]:
# Reminder: You are now done with step 1 of Round 2 on predicting the conditional amount.
# Next, to complete Round2, you need to perform step 2 to predict the probability of giving, calculate the uplift and prepare your decision.

In [75]:
!head Round2_Output_amt.csv

ID,AmtContact,AmtNoContact
2000001,66.93424630053266,69.23984220155863
2000002,60.77636705786858,63.08196295889454
2000003,69.5998558796027,71.90545178062865
2000004,39.476624792933166,41.782220693959125
2000005,74.9924262705656,77.29802217159157
2000006,33.27624889879617,35.58184479982213
2000007,38.99575930698653,41.30135520801248
2000008,60.362432358169855,62.668028259195815
2000009,39.125353083996714,41.43094898502268